// Mocks generated by Mockito 5.4.5 from annotations
// in hotelmangement/test/features/hotel_management/domain/usecases/table/create_table_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i2;
import 'package:hotelmangement/core/error/failure.dart' as _i6;
import 'package:hotelmangement/features/hotel_management/domain/entities/hotel.dart'
    as _i9;
import 'package:hotelmangement/features/hotel_management/domain/entities/table.dart'
    as _i7;
import 'package:hotelmangement/features/hotel_management/domain/repositories/hotel_repository.dart'
    as _i3;
import 'package:hotelmangement/features/hotel_management/domain/repositories/hotel_table_repository.dart'
    as _i4;
import 'package:hotelmangement/features/hotel_management/domain/usecases/validation/hotel_authorize.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHotelRepository_1 extends _i1.SmartFake
    implements _i3.HotelRepository {
  _FakeHotelRepository_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [HotelTableRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHotelTableRepository extends _i1.Mock
    implements _i4.HotelTableRepository {
  MockHotelTableRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i7.Table>> createTable({
    required String? hotelId,
    required String? tableNumber,
    required int? space,
    required String? floor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createTable, [], {
              #hotelId: hotelId,
              #tableNumber: tableNumber,
              #space: space,
              #floor: floor,
            }),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, _i7.Table>>.value(
              _FakeEither_0<_i6.Failure, _i7.Table>(
                this,
                Invocation.method(#createTable, [], {
                  #hotelId: hotelId,
                  #tableNumber: tableNumber,
                  #space: space,
                  #floor: floor,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, _i7.Table>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i7.Table>> updateTable({
    required String? tableId,
    required String? hotelId,
    String? tableNumber,
    String? description,
    String? space,
    String? floor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateTable, [], {
              #tableId: tableId,
              #hotelId: hotelId,
              #tableNumber: tableNumber,
              #description: description,
              #space: space,
              #floor: floor,
            }),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, _i7.Table>>.value(
              _FakeEither_0<_i6.Failure, _i7.Table>(
                this,
                Invocation.method(#updateTable, [], {
                  #tableId: tableId,
                  #hotelId: hotelId,
                  #tableNumber: tableNumber,
                  #description: description,
                  #space: space,
                  #floor: floor,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, _i7.Table>>);

  @override
  _i5.Future<void> deleteTable({
    required String? tableId,
    required String? hotelId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTable, [], {
              #tableId: tableId,
              #hotelId: hotelId,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i7.Table>>> getTables({
    required String? hotelId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTables, [], {#hotelId: hotelId}),
            returnValue:
                _i5.Future<_i2.Either<_i6.Failure, List<_i7.Table>>>.value(
                  _FakeEither_0<_i6.Failure, List<_i7.Table>>(
                    this,
                    Invocation.method(#getTables, [], {#hotelId: hotelId}),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, List<_i7.Table>>>);
}

/// A class which mocks [HotelAuthorize].
///
/// See the documentation for Mockito's code generation for more information.
class MockHotelAuthorize extends _i1.Mock implements _i8.HotelAuthorize {
  MockHotelAuthorize() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.HotelRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeHotelRepository_1(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.HotelRepository);

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i9.Hotel>> call(_i8.Params? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i5.Future<_i2.Either<_i6.Failure, _i9.Hotel>>.value(
              _FakeEither_0<_i6.Failure, _i9.Hotel>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, _i9.Hotel>>);
}
