class HotelModel {
  final String name, image, description, package, location,category;
  final double rating;
  final int review, price, bed, bathroom, Mobile;
  List<String> Facilities;

  HotelModel({
    required this.name,
    required this.image,
    required this.description,
    required this.package,
    required this.location,
    required this.rating,
    required this.review,
    required this.price,
    required this.bed,
    required this.bathroom,
    required this.Mobile,
    required this.Facilities,
    required this.category, required String id
  });
}

// List<HotelModel> hotelModel = [
//   HotelModel(
//       name: "Aventra Hotel",
//       image: "assets/hotels/hilton.jpg",
//       location: "Colombo 07",
//       rating: 4.7,
//       review: 1200,
//       price: 3500,
//       description:
//           "A luxurious stay with modern amenities and breathtaking views in the heart of the city.",
//       package: "Day",
//       bed: 3,
//       bathroom: 4,
//       Mobile: 0777123456,
//       Facilities: ["AC", "Restaurant", "Swimming Pool", "24 Hours Front Desk"],
//       category : "Resorts",
//       ),
//   HotelModel(
//       name: "Grand Ocean Hotel",
//       image: "assets/hotels/hilton.jpg",
//       location: "Galle Face, Colombo",
//       rating: 4.6,
//       review: 980,
//       price: 3200,
//       description:
//           "Enjoy a beachfront retreat with world-class service and exquisite dining options.",
//       package: "Night",
//       bed: 2,
//       bathroom: 3,
//       Mobile: 0777123457,
//       Facilities: ["AC", "Restaurant", "Beach Access", "Bar"],
//       category : "Resorts",),
//   HotelModel(
//       name: "Serene Paradise Hotel",
//       image: "assets/hotels/hilton.jpg",
//       location: "Kandy Hills",
//       rating: 4.8,
//       review: 1500,
//       price: 4000,
//       description:
//           "A peaceful getaway surrounded by lush greenery and scenic mountain views.",
//       package: "Weekend",
//       bed: 4,
//       bathroom: 5,
//       Mobile: 0777123458,
//       Facilities: ["AC", "Restaurant", "Swimming Pool", "Gym"],
//       category : "Villas"),
//   HotelModel(
//       name: "Royal Orchid Resort",
//       image: "assets/hotels/hilton.jpg",
//       location: "Bentota Beach",
//       rating: 4.5,
//       review: 890,
//       price: 2800,
//       description:
//           "An elegant beachside resort with spa treatments and water sports activities.",
//       package: "All-Inclusive",
//       bed: 3,
//       bathroom: 3,
//       Mobile: 0777123459,
//       Facilities: ["AC", "Restaurant", "Swimming Pool", "Spa"],
//       category : "Villas"
//       ),
//   HotelModel(
//       name: "Skyline Towers Hotel",
//       image: "assets/hotels/hilton.jpg",
//       location: "Colombo City Center",
//       rating: 4.9,
//       review: 2000,
//       price: 5000,
//       description:
//           "A premium high-rise hotel offering panoramic city views and luxury accommodations.",
//       package: "Business",
//       bed: 2,
//       bathroom: 2,
//       Mobile: 0777123460,
//       Facilities: ["AC", "Restaurant", "Gym", "Business Center"],
//       category : "Luxury Hotels"),
//        HotelModel(
//       name: "Aventra Hotel",
//       image: "assets/hotels/hilton.jpg",
//       location: "Colombo 07",
//       rating: 4.7,
//       review: 1200,
//       price: 3500,
//       description:
//           "A luxurious stay with modern amenities and breathtaking views in the heart of the city.",
//       package: "Day",
//       bed: 3,
//       bathroom: 4,
//       Mobile: 0777123456,
//       Facilities: ["AC", "Restaurant", "Swimming Pool", "24 Hours Front Desk"],
//       category : "Resorts",
//       ),
//   HotelModel(
//       name: "Grand Ocean Hotel",
//       image: "assets/hotels/hilton.jpg",
//       location: "Galle Face, Colombo",
//       rating: 4.6,
//       review: 980,
//       price: 3200,
//       description:
//           "Enjoy a beachfront retreat with world-class service and exquisite dining options.",
//       package: "Night",
//       bed: 2,
//       bathroom: 3,
//       Mobile: 0777123457,
//       Facilities: ["AC", "Restaurant", "Beach Access", "Bar"],
//       category : "Resorts",),
//   HotelModel(
//       name: "Serene Paradise Hotel",
//       image: "assets/hotels/hilton.jpg",
//       location: "Kandy Hills",
//       rating: 4.8,
//       review: 1500,
//       price: 4000,
//       description:
//           "A peaceful getaway surrounded by lush greenery and scenic mountain views.",
//       package: "Weekend",
//       bed: 4,
//       bathroom: 5,
//       Mobile: 0777123458,
//       Facilities: ["AC", "Restaurant", "Swimming Pool", "Gym"],
//       category : "Villas"),
//   HotelModel(
//       name: "Royal Orchid Resort",
//       image: "assets/hotels/hilton.jpg",
//       location: "Bentota Beach",
//       rating: 4.5,
//       review: 890,
//       price: 2800,
//       description:
//           "An elegant beachside resort with spa treatments and water sports activities.",
//       package: "All-Inclusive",
//       bed: 3,
//       bathroom: 3,
//       Mobile: 0777123459,
//       Facilities: ["AC", "Restaurant", "Swimming Pool", "Spa"],
//       category : "Villas"
//       ),
//   HotelModel(
//       name: "Skyline Towers Hotel",
//       image: "assets/hotels/hilton.jpg",
//       location: "Colombo City Center",
//       rating: 4.9,
//       review: 2000,
//       price: 5000,
//       description:
//           "A premium high-rise hotel offering panoramic city views and luxury accommodations.",
//       package: "Business",
//       bed: 2,
//       bathroom: 2,
//       Mobile: 0777123460,
//       Facilities: ["AC", "Restaurant", "Gym", "Business Center"],
//       category : "Luxury Hotels"),
//        HotelModel(
//       name: "Aventra Hotel",
//       image: "assets/hotels/hilton.jpg",
//       location: "Colombo 07",
//       rating: 4.7,
//       review: 1200,
//       price: 3500,
//       description:
//           "A luxurious stay with modern amenities and breathtaking views in the heart of the city.",
//       package: "Day",
//       bed: 3,
//       bathroom: 4,
//       Mobile: 0777123456,
//       Facilities: ["AC", "Restaurant", "Swimming Pool", "24 Hours Front Desk"],
//       category : "Resorts",
//       ),
//   HotelModel(
//       name: "Grand Ocean Hotel",
//       image: "assets/hotels/hilton.jpg",
//       location: "Galle Face, Colombo",
//       rating: 4.6,
//       review: 980,
//       price: 3200,
//       description:
//           "Enjoy a beachfront retreat with world-class service and exquisite dining options.",
//       package: "Night",
//       bed: 2,
//       bathroom: 3,
//       Mobile: 0777123457,
//       Facilities: ["AC", "Restaurant", "Beach Access", "Bar"],
//       category : "Resorts",),
//   HotelModel(
//       name: "Serene Paradise Hotel",
//       image: "assets/hotels/hilton.jpg",
//       location: "Kandy Hills",
//       rating: 4.8,
//       review: 1500,
//       price: 4000,
//       description:
//           "A peaceful getaway surrounded by lush greenery and scenic mountain views.",
//       package: "Weekend",
//       bed: 4,
//       bathroom: 5,
//       Mobile: 0777123458,
//       Facilities: ["AC", "Restaurant", "Swimming Pool", "Gym"],
//       category : "Villas"),
//   HotelModel(
//       name: "Royal Orchid Resort",
//       image: "assets/hotels/hilton.jpg",
//       location: "Bentota Beach",
//       rating: 4.5,
//       review: 890,
//       price: 2800,
//       description:
//           "An elegant beachside resort with spa treatments and water sports activities.",
//       package: "All-Inclusive",
//       bed: 3,
//       bathroom: 3,
//       Mobile: 0777123459,
//       Facilities: ["AC", "Restaurant", "Swimming Pool", "Spa"],
//       category : "Villas"
//       ),
//   HotelModel(
//       name: "Skyline Towers Hotel",
//       image: "assets/hotels/hilton.jpg",
//       location: "Colombo City Center",
//       rating: 4.9,
//       review: 2000,
//       price: 5000,
//       description:
//           "A premium high-rise hotel offering panoramic city views and luxury accommodations.",
//       package: "Business",
//       bed: 2,
//       bathroom: 2,
//       Mobile: 0777123460,
//       Facilities: ["AC", "Restaurant", "Gym", "Business Center"],
//       category : "Luxury Hotels"),
//        HotelModel(
//       name: "Aventra Hotel",
//       image: "assets/hotels/hilton.jpg",
//       location: "Colombo 07",
//       rating: 4.7,
//       review: 1200,
//       price: 3500,
//       description:
//           "A luxurious stay with modern amenities and breathtaking views in the heart of the city.",
//       package: "Day",
//       bed: 3,
//       bathroom: 4,
//       Mobile: 0777123456,
//       Facilities: ["AC", "Restaurant", "Swimming Pool", "24 Hours Front Desk"],
//       category : "Resorts",
//       ),
//   HotelModel(
//       name: "Grand Ocean Hotel",
//       image: "assets/hotels/hilton.jpg",
//       location: "Galle Face, Colombo",
//       rating: 4.6,
//       review: 980,
//       price: 3200,
//       description:
//           "Enjoy a beachfront retreat with world-class service and exquisite dining options.",
//       package: "Night",
//       bed: 2,
//       bathroom: 3,
//       Mobile: 0777123457,
//       Facilities: ["AC", "Restaurant", "Beach Access", "Bar"],
//       category : "Resorts",),
//   HotelModel(
//       name: "Serene Paradise Hotel",
//       image: "assets/hotels/hilton.jpg",
//       location: "Kandy Hills",
//       rating: 4.8,
//       review: 1500,
//       price: 4000,
//       description:
//           "A peaceful getaway surrounded by lush greenery and scenic mountain views.",
//       package: "Weekend",
//       bed: 4,
//       bathroom: 5,
//       Mobile: 0777123458,
//       Facilities: ["AC", "Restaurant", "Swimming Pool", "Gym"],
//       category : "Villas"),
//   HotelModel(
//       name: "Royal Orchid Resort",
//       image: "assets/hotels/hilton.jpg",
//       location: "Bentota Beach",
//       rating: 4.5,
//       review: 890,
//       price: 2800,
//       description:
//           "An elegant beachside resort with spa treatments and water sports activities.",
//       package: "All-Inclusive",
//       bed: 3,
//       bathroom: 3,
//       Mobile: 0777123459,
//       Facilities: ["AC", "Restaurant", "Swimming Pool", "Spa"],
//       category : "Villas"
//       ),
//   HotelModel(
//       name: "Skyline Towers Hotel",
//       image: "assets/hotels/hilton.jpg",
//       location: "Colombo City Center",
//       rating: 4.9,
//       review: 2000,
//       price: 5000,
//       description:
//           "A premium high-rise hotel offering panoramic city views and luxury accommodations.",
//       package: "Business",
//       bed: 2,
//       bathroom: 2,
//       Mobile: 0777123460,
//       Facilities: ["AC", "Restaurant", "Gym", "Business Center"],
//       category : "Luxury Hotels"),
//        HotelModel(
//       name: "Aventra Hotel",
//       image: "assets/hotels/hilton.jpg",
//       location: "Colombo 07",
//       rating: 4.7,
//       review: 1200,
//       price: 3500,
//       description:
//           "A luxurious stay with modern amenities and breathtaking views in the heart of the city.",
//       package: "Day",
//       bed: 3,
//       bathroom: 4,
//       Mobile: 0777123456,
//       Facilities: ["AC", "Restaurant", "Swimming Pool", "24 Hours Front Desk"],
//       category : "Resorts",
//       ),
//   HotelModel(
//       name: "Grand Ocean Hotel",
//       image: "assets/hotels/hilton.jpg",
//       location: "Galle Face, Colombo",
//       rating: 4.6,
//       review: 980,
//       price: 3200,
//       description:
//           "Enjoy a beachfront retreat with world-class service and exquisite dining options.",
//       package: "Night",
//       bed: 2,
//       bathroom: 3,
//       Mobile: 0777123457,
//       Facilities: ["AC", "Restaurant", "Beach Access", "Bar"],
//       category : "Resorts",),
//   HotelModel(
//       name: "Serene Paradise Hotel",
//       image: "assets/hotels/hilton.jpg",
//       location: "Kandy Hills",
//       rating: 4.8,
//       review: 1500,
//       price: 4000,
//       description:
//           "A peaceful getaway surrounded by lush greenery and scenic mountain views.",
//       package: "Weekend",
//       bed: 4,
//       bathroom: 5,
//       Mobile: 0777123458,
//       Facilities: ["AC", "Restaurant", "Swimming Pool", "Gym"],
//       category : "Villas"),
//   HotelModel(
//       name: "Royal Orchid Resort",
//       image: "assets/hotels/hilton.jpg",
//       location: "Bentota Beach",
//       rating: 4.5,
//       review: 890,
//       price: 2800,
//       description:
//           "An elegant beachside resort with spa treatments and water sports activities.",
//       package: "All-Inclusive",
//       bed: 3,
//       bathroom: 3,
//       Mobile: 0777123459,
//       Facilities: ["AC", "Restaurant", "Swimming Pool", "Spa"],
//       category : "Villas"
//       ),
//   HotelModel(
//       name: "Skyline Towers Hotel",
//       image: "assets/hotels/hilton.jpg",
//       location: "Colombo City Center",
//       rating: 4.9,
//       review: 2000,
//       price: 5000,
//       description:
//           "A premium high-rise hotel offering panoramic city views and luxury accommodations.",
//       package: "Business",
//       bed: 2,
//       bathroom: 2,
//       Mobile: 0777123460,
//       Facilities: ["AC", "Restaurant", "Gym", "Business Center"],
//       category : "Luxury Hotels"),
//        HotelModel(
//       name: "Aventra Hotel",
//       image: "assets/hotels/hilton.jpg",
//       location: "Colombo 07",
//       rating: 4.7,
//       review: 1200,
//       price: 3500,
//       description:
//           "A luxurious stay with modern amenities and breathtaking views in the heart of the city.",
//       package: "Day",
//       bed: 3,
//       bathroom: 4,
//       Mobile: 0777123456,
//       Facilities: ["AC", "Restaurant", "Swimming Pool", "24 Hours Front Desk"],
//       category : "Resorts",
//       ),
//   HotelModel(
//       name: "Grand Ocean Hotel",
//       image: "assets/hotels/hilton.jpg",
//       location: "Galle Face, Colombo",
//       rating: 4.6,
//       review: 980,
//       price: 3200,
//       description:
//           "Enjoy a beachfront retreat with world-class service and exquisite dining options.",
//       package: "Night",
//       bed: 2,
//       bathroom: 3,
//       Mobile: 0777123457,
//       Facilities: ["AC", "Restaurant", "Beach Access", "Bar"],
//       category : "Resorts",),
//   HotelModel(
//       name: "Serene Paradise Hotel",
//       image: "assets/hotels/hilton.jpg",
//       location: "Kandy Hills",
//       rating: 4.8,
//       review: 1500,
//       price: 4000,
//       description:
//           "A peaceful getaway surrounded by lush greenery and scenic mountain views.",
//       package: "Weekend",
//       bed: 4,
//       bathroom: 5,
//       Mobile: 0777123458,
//       Facilities: ["AC", "Restaurant", "Swimming Pool", "Gym"],
//       category : "Villas"),
//   HotelModel(
//       name: "Royal Orchid Resort",
//       image: "assets/hotels/hilton.jpg",
//       location: "Bentota Beach",
//       rating: 4.5,
//       review: 890,
//       price: 2800,
//       description:
//           "An elegant beachside resort with spa treatments and water sports activities.",
//       package: "All-Inclusive",
//       bed: 3,
//       bathroom: 3,
//       Mobile: 0777123459,
//       Facilities: ["AC", "Restaurant", "Swimming Pool", "Spa"],
//       category : "Villas"
//       ),
//   HotelModel(
//       name: "Skyline Towers Hotel",
//       image: "assets/hotels/hilton.jpg",
//       location: "Colombo City Center",
//       rating: 4.9,
//       review: 2000,
//       price: 5000,
//       description:
//           "A premium high-rise hotel offering panoramic city views and luxury accommodations.",
//       package: "Business",
//       bed: 2,
//       bathroom: 2,
//       Mobile: 0777123460,
//       Facilities: ["AC", "Restaurant", "Gym", "Business Center"],
//       category : "Luxury Hotels"),
//        HotelModel(
//       name: "Aventra Hotel",
//       image: "assets/hotels/hilton.jpg",
//       location: "Colombo 07",
//       rating: 4.7,
//       review: 1200,
//       price: 3500,
//       description:
//           "A luxurious stay with modern amenities and breathtaking views in the heart of the city.",
//       package: "Day",
//       bed: 3,
//       bathroom: 4,
//       Mobile: 0777123456,
//       Facilities: ["AC", "Restaurant", "Swimming Pool", "24 Hours Front Desk"],
//       category : "Resorts",
//       ),
//   HotelModel(
//       name: "Grand Ocean Hotel",
//       image: "assets/hotels/hilton.jpg",
//       location: "Galle Face, Colombo",
//       rating: 4.6,
//       review: 980,
//       price: 3200,
//       description:
//           "Enjoy a beachfront retreat with world-class service and exquisite dining options.",
//       package: "Night",
//       bed: 2,
//       bathroom: 3,
//       Mobile: 0777123457,
//       Facilities: ["AC", "Restaurant", "Beach Access", "Bar"],
//       category : "Resorts",),
//   HotelModel(
//       name: "Serene Paradise Hotel",
//       image: "assets/hotels/hilton.jpg",
//       location: "Kandy Hills",
//       rating: 4.8,
//       review: 1500,
//       price: 4000,
//       description:
//           "A peaceful getaway surrounded by lush greenery and scenic mountain views.",
//       package: "Weekend",
//       bed: 4,
//       bathroom: 5,
//       Mobile: 0777123458,
//       Facilities: ["AC", "Restaurant", "Swimming Pool", "Gym"],
//       category : "Villas"),
//   HotelModel(
//       name: "Royal Orchid Resort",
//       image: "assets/hotels/hilton.jpg",
//       location: "Bentota Beach",
//       rating: 4.5,
//       review: 890,
//       price: 2800,
//       description:
//           "An elegant beachside resort with spa treatments and water sports activities.",
//       package: "All-Inclusive",
//       bed: 3,
//       bathroom: 3,
//       Mobile: 0777123459,
//       Facilities: ["AC", "Restaurant", "Swimming Pool", "Spa"],
//       category : "Villas"
//       ),
//   HotelModel(
//       name: "Skyline Towers Hotel",
//       image: "assets/hotels/hilton.jpg",
//       location: "Colombo City Center",
//       rating: 4.9,
//       review: 2000,
//       price: 5000,
//       description:
//           "A premium high-rise hotel offering panoramic city views and luxury accommodations.",
//       package: "Business",
//       bed: 2,
//       bathroom: 2,
//       Mobile: 0777123460,
//       Facilities: ["AC", "Restaurant", "Gym", "Business Center"],
//       category : "Luxury Hotels"),
// ];
