spring:
  config:
    import:
      optional:file:.env[.properties]
  application:
    name: hotelManagement

  datasource:
    url: ${HOTEL_MANAGEMENT_DATABASE_JDBC_URL}
    username: ${HOTEL_MANAGEMENT_DATABASE_USERNAME}
    password: ${HOTEL_MANAGEMENT_DATABASE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl_auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql